import random


def dungeon_size():
    """
    This function decides the size of the map and runs all
    the individual dungeon generation functions
    """
    print("defining dungeon size...\n")
    size = input("how large would you like the dungeon to be? S, M or L?\n")
    sizef = size[0]
    if "s" in sizef.lower():
        print("Creating a small dungeon")
        init_dungeon(20, 40)
        init_rooms(random.randint(8, 12), 20)
    elif "m" in sizef.lower():
        print("Creating a medium dungeon")
        init_dungeon(50, 50)
        init_rooms(random.randint(20, 30), 50)
    elif "l" in sizef.lower():
        print("Creating a large dungeon")
        init_dungeon(100, 100)
        init_rooms(random.randint(50, 70), 100)
    else:
        print("that's not a valid size you muppet")


def init_dungeon(d_width, d_height):
    """
    This function sets every square in the dungeon to wall
    dungeon size generated by the dungeon size function
    """
    print("Generating dungeon map...")

    dungeon_map = {}
    for xcoord in range(d_width):
        for ycoord in range(d_height):
            dungeon_map[xcoord, ycoord] = 0
    print("map generated!")
    return dungeon_map


def init_rooms(room_number, dungeon_width):
    """
    This function adds x rooms to the dungeon
    """
    rooms = {}
    for room in range(room_number):
        room_height = random.randint(4,6)
        room_width = random.randint(4,6)
        rooms[room] = room_height, room_width
    print(rooms)



def main():
    dungeon_size()

main()


